# Generated by Django 4.1.3 on 2023-03-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_movie_overview_movie_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.IntegerField(max_length=200),
        ),
    ]
